from langchain_ollama import ChatOllama
from langchain_openai import ChatOpenAI
from langchain.agents import create_agent

from tools.get_objective import get_objective, get_all_objectives
from tools.get_prompts import get_final_prompt
from tools.kid_problem_apis import prepare_problems

import logging
import sys
import datetime

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[ logging.StreamHandler(stream=sys.stdout) ]
)
logger = logging.getLogger(__name__)


# llm = ChatOllama(model="qwen3-coder:latest")
llm = ChatOpenAI(model="gpt-4o-mini")

tools = [get_objective, get_final_prompt, prepare_problems]

instructions = """
You are an educational assistant. 
When a user asks for generating math practice problems, you MUST:
1. User should give a specific objective number, use the 'get_objective' tool to find the specific objective. Stop if user does not give you this information.
2. Once you have the objective, use the 'get_final_prompt' tool to get the prompt for generating math practice problems
3. Use the 'prepare_problems' tool to convert the raw json text of problems generated by LLM into a list of Problem instances that can be ingested by KidProblem API. 
4. Provide the final math problems which are ready to be sent to KidProblem API to the user. Make sure the final math problems are in JSON format and follow the structure required by KidProblem API.
"""

query = "I want to generate math practice problem using the learning objective 6 for math CBE test."

agent = create_agent(
    model=llm,
    tools=tools,
    system_prompt=instructions
)

result = agent.invoke({"messages": [{"role": "user", "content": query}]})

problems = result["messages"][-1].content
with open(f"problems-{datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")}.log", "w", encoding="utf-8") as f:
    f.write(problems)
print(problems)
