from typing import List
from langchain_core.tools import tool, ToolException
from models.problem_model import Problem
import json
import re
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

DEFAULT_PROBLEM_CATEGORY = "HOME"
DEFAULT_PROBLEM_TAG = "CBE6"
DEFAULT_ANSWER_OPTIONS = "A,B,C,D"


@tool()
def prepare_problems(raw_json: str, start_num = 1, problem_year = '') -> List[Problem]:
    """
    Prepare raw json text of problems generated by LLM for KidProblem API consumption.

    Args:
        raw_json (str): A string containing raw problem data in JSON format.
        start_num (int): start_num is used to generate ProblemNumber, which is part of KidProblem problem identifier. If not provided, it will start from 1.
        problem_year (str): problem_year will be populated as ProblemYear, which is part of KidProblem problem identifier. It can be any string. If not provided, it will be set to "C" followed by the current date in MMDD format, e.g., "C0420" for April 20th.
    Returns:
        List[Problem]: A list of cleaned Problem instances.
    """
    
    logger.debug(f"Preparing problems for KidProblem API with start_num={start_num} and problem_year={problem_year}...")
    logger.debug(f"Raw JSON input: {raw_json}")
    
    try:   
        raw_problems = json.loads(raw_json)
    except json.JSONDecodeError:
        raise ToolException(f"Invalid JSON format for the argument raw_json: {raw_json}")

    if not isinstance(raw_problems, list):
        raise ToolException(f"The argument raw_json cannot be parsed as a Json array: {raw_json}")

    if not problem_year:
        problem_year = f"C{datetime.today().strftime('%m%d')}"

    problems = []
    for raw in raw_problems:
        if "ProblemText" not in raw:
            logger.debug("Wrong input ... ")
            logger.debug(raw)
            continue

        problem_title = f"{DEFAULT_PROBLEM_CATEGORY}-{problem_year}-{str(start_num).rjust(3, '0')}"
        
        problem = Problem(
            ProblemCategory=DEFAULT_PROBLEM_CATEGORY,
            ProblemYear=problem_year,
            ProblemNumber=str(start_num).rjust(3, "0"),
            ProblemTitle=problem_title,
            ProblemText=process_problem_text(raw["ProblemText"], problem_title),
            AnswerOptions=raw.get("AnswerOptions", DEFAULT_ANSWER_OPTIONS),
            ProblemAnswer=raw.get("ProblemAnswer", ''),
            ProblemTags=[raw.get("ProblemTags", DEFAULT_PROBLEM_TAG)],
            SolutionText="",
            IsStaging=True,
            Action=1
        )
        start_num += 1
        problems.append(problem)
    
    logger.debug(f"Prepared {len(problems)} problems for KidProblem API.")
    logger.debug(problems)
    return problems


def process_problem_text(raw_text:str, problem_title:str) -> str :
    cleaned = raw_text
    cleaned = cleaned.replace('\\n', '</br>\n')
    cleaned = cleaned.replace('PlaceHolder', problem_title)
    cleaned = cleaned.replace(r'\\\\', r'\\').replace(r'\\\"', r'\"') 
    cleaned = re.sub(r'\\\\(?![\s])', r'\\', cleaned)
    return cleaned

prepare_problems.handle_tool_error=True